export const CODES = {
  AUTH: {
    INVALID_EMAIL: 'INVALID_EMAIL',
    EMPTY_EMAIL: 'EMPTY_EMAIL',
    EXIST_EMAIL: 'EXIST_EMAIL',
    EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',

    EMPTY_PASSWORD: 'EMPTY_PASSWORD',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    WRONG_PASSWORD: 'WRONG_PASSWORD',

    INACTIVE_ACCOUNT: 'INACTIVE_ACCOUNT',
    ACTIVE_ACCOUNT: 'ACTIVE_ACCOUNT',

    EMPTY_FULLNAME: 'EMPTY_FULLNAME',
    INVALID_FULLNAME: 'INVALID_FULLNAME',
    
    EMPTY_OTP: 'EMPTY_OTP',
    INVALID_OTP: 'INVALID_OTP',
    NEW_OTP_GENERATED: 'NEW_OTP_GENERATED',
    WRONG_OTP: 'WRONG_OTP',
    CORRECT_OTP: 'CORRECT_OTP',

    PASSWORD_NOT_MATCH: 'PASSWORD_NOT_MATCH',
    PASSWORD_RESET: 'PASSWORD_RESET',
    OTP_NOT_FOUND: 'OTP_NOT_FOUND',
  }
}