export const CODES = {
  AUTH: {
    INVALID_EMAIL: 'INVALID_EMAIL',
    EMPTY_EMAIL: 'EMPTY_EMAIL',
    EXIST_EMAIL: 'EXIST_EMAIL',
    EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',

    EMPTY_PASSWORD: 'EMPTY_PASSWORD',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    WRONG_PASSWORD: 'WRONG_PASSWORD',

    INACTIVE_ACCOUNT: 'INACTIVE_ACCOUNT',
    ACTIVE_ACCOUNT: 'ACTIVE_ACCOUNT',

    EMPTY_FULLNAME: 'EMPTY_FULLNAME',
    INVALID_FULLNAME: 'INVALID_FULLNAME',
    
    EMPTY_OTD: 'EMPTY_OTD',
    INVALID_OTD: 'INVALID_OTD',
    NEW_OTD_GENERATED: 'NEW_OTD_GENERATED',
    WRONG_OTD: 'WRONG_OTD',
  }
}